title: Embedded Software Web Site
description: Electric Power Steering Blog
remote_theme: just-the-docs/just-the-docs

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"

url: ""
plugins:
  - jekyll-sitemap
  - jekyll-remote-theme